export { default as bannerImg } from './banner-backgroud.jpg'
export { default as weightsImg } from './weights-category.jpg'
export { default as cardioImg } from './cardio-category.jpg'
export { default as apparelImg } from './apparel-category.jpg'
export { default as gearImg } from './gear-category.jpg'
